name: Tests
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    env:
      TOOLS_DIRECTORY: tools
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Run a specific Cake script
        uses: ./
        with:
          script-path: build.cake
      - name: Run a specific target
        uses: ./
        with:
          target: Successful-Task
      - name: Remove the tools directory
        run: rm -rf $TOOLS_DIRECTORY
        shell: bash
      - name: Run with a specific Cake version
        env:
          EXPECTED_CAKE_VERSION: 0.34.1
        uses: ./
        with:
          cake-version: 0.34.1
          target: Test-Cake-Version
      - name: Run with a different Cake version in the same build
        env:
          EXPECTED_CAKE_VERSION: 0.33.0
        uses: ./
        with:
          cake-version: 0.33.0
          target: Test-Cake-Version
      - name: Run bootstrapping of Cake module
        uses: ./
        with:
          cake-bootstrap: true
          script-path: module.cake
      - name: Run with a specific verbosity level
        uses: ./
        env:
          EXPECTED_VERBOSITY: Diagnostic
        with:
          verbosity: Diagnostic
          target: Test-Verbosity
      - name: Run with custom script parameters
        uses: ./
        env:
          EXPECTED_STRING_ARGUMENT: '''value'''
          EXPECTED_NUMERIC_ARGUMENT: '3'
          EXPECTED_BOOLEAN_ARGUMENT: 'true'
        with:
          script-path: build.cake
          target: Test-Script-Parameters
          arguments: |
            string-parameter: 'value'
            numeric-parameter: 3
            boolean-parameter: true
